---
- name: Install software on ubuntu servers
  hosts: [dev_servers]
  tasks:
   - name: install nginx
     apt: name=nginx state=present update_cache=yes
     
   - name: install wget
     apt: name=wget state=latest update_cache=yes
