---
- name: install jenkins on centos
  hosts: localhost
  become: yes
  become_user: root
  tasks:
   - name: Download Longterm jenkins release
     get_url: 
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

   - name: import jenkins key
     rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

   - name: yum repo update
     yum:
      name: '*'
      state: latest

   - name: install java
     yum:
      name: java-11*
      state: present

   - name: install jenkins
     yum:
      name: jenkins
      state: latest

   - name: daemon-reload to pickup the changes we did
     systemd:
      daemon_reload: yes

   - name: service jenkins start
     systemd: 
      name: jenkins
      state: started

